# image will be published to ghcr.io/<user>/<name>
name: ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
      - https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
    install:
      - morewaita-icon-theme
      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-appindicator
      # - gnome-shell-extension-blur-my-shell
      - zsh
      - neovim
      - lsd
      - fd-find
      - blackbox-terminal
      - steam-devices
      - nautilus-python
      - tmux
      - bat
      - gh
      - socat
      - wl-clipboard
      - virt-manager
      - virtio-win
      - ddcutil
      # Codecs
      - gstreamer1-plugin-openh264
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - mesa-vdpau-drivers-freeworld
    remove:
      # Remove GNOME Terminal in favor of BlackBox
      - gnome-terminal
      - gnome-terminal-nautilus

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - net.nokyan.Resources
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    system:
      repo-url: https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo
      repo-name: flathub-beta
      repo-title: "Flathub (beta) (system-wide)"
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-title: "Flathub (user-specific)"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: script
    scripts:
      # adds xdg-terminal-exec and sets BlackBox as default terminal
      - blackbox.sh
      # allow DDC control of external monitors
      - ddcutil.sh

  - type: bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - gnome-vrr # enables gnome-vrr for your image
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section
